**# IMPORTING LIBRARIES**

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import kagglehub

In [2]:
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

Using Colab cache for faster access to the 'new-plant-diseases-dataset' dataset.


In [3]:
print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/new-plant-diseases-dataset


**# DATA PRE_PROCESSING**

In [5]:
training_path = "/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train"

In [7]:
training_set = tf.keras.utils.image_dataset_from_directory(
    training_path,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


In [9]:
validation_path = "/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid"

In [10]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    validation_path,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [11]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [12]:
validation_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [14]:
for x,y in training_set:
  print(x, x.shape)
  print(y, y.shape)
  break

tf.Tensor(
[[[[146.5  137.5  140.5 ]
   [172.25 163.25 166.25]
   [170.   161.   164.  ]
   ...
   [ 18.25  17.25  22.25]
   [ 14.75  15.75  19.75]
   [ 20.75  21.75  25.75]]

  [[165.5  156.5  159.5 ]
   [164.75 155.75 158.75]
   [177.5  168.5  171.5 ]
   ...
   [ 19.    18.    23.  ]
   [ 17.5   18.5   22.5 ]
   [ 18.5   19.5   23.5 ]]

  [[168.25 159.25 162.25]
   [174.   165.   168.  ]
   [134.75 125.75 128.75]
   ...
   [ 17.75  16.75  21.75]
   [ 18.75  19.75  23.75]
   [ 18.    19.    23.  ]]

  ...

  [[193.75 185.75 183.75]
   [204.   196.   194.  ]
   [200.   192.   190.  ]
   ...
   [201.75 190.75 194.75]
   [170.   159.   163.  ]
   [159.25 148.25 152.25]]

  [[200.5  192.5  190.5 ]
   [211.25 203.25 201.25]
   [190.5  182.5  180.5 ]
   ...
   [167.25 156.25 160.25]
   [168.25 157.25 161.25]
   [158.   147.   151.  ]]

  [[199.   191.   189.  ]
   [190.   182.   180.  ]
   [202.25 194.25 192.25]
   ...
   [186.25 175.25 179.25]
   [157.75 146.75 150.75]
   [176.5  165.5  16

**# BUILDING A MODEL**

In [46]:
model = tf.keras.Sequential()

In [47]:
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3]))
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [48]:
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [49]:
model.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=128, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [50]:
model.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=256, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [51]:
model.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, padding="same", activation="relu"))
model.add(tf.keras.layers.Conv2D(filters=512, kernel_size=3, activation="relu"))
model.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [52]:
model.add(tf.keras.layers.Flatten())

In [53]:
model.add(tf.keras.layers.Dense(units=1500, activation="relu"))

In [54]:
model.add(tf.keras.layers.Dense(units=38, activation="softmax"))

In [55]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [56]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_20 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_21 (Conv2D)              │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_9 (MaxPooling2D)  │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_22 (Conv2D)              │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_23 (Conv2D)              │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_10 (MaxPooling2D) │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_24 (Conv2D)              │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_25 (Conv2D)              │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_11 (MaxPooling2D) │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_26 (Conv2D)              │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_27 (Conv2D)              │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_28 (Conv2D)              │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_29 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

**# TRAINING A MODEL**

In [57]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 227s 68ms/step - accuracy: 0.5136 - loss: 1.7007 - val_accuracy: 0.8540 - val_loss: 0.4558
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 143s 65ms/step - accuracy: 0.8788 - loss: 0.3796 - val_accuracy: 0.9049 - val_loss: 0.3033
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 196s 63ms/step - accuracy: 0.9306 - loss: 0.2099 - val_accuracy: 0.9255 - val_loss: 0.2277
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 137s 62ms/step - accuracy: 0.9522 - loss: 0.1415 - val_accuracy: 0.9373 - val_loss: 0.2054
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 137s 62ms/step - accuracy: 0.9655 - loss: 0.1028 - val_accuracy: 0.9501 - val_loss: 0.1690
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 142s 63ms/step - accuracy: 0.9730 - loss: 0.0839 - val_accuracy: 0.9574 - val_loss: 0.1442
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 142s 62ms/step - accuracy: 0.9765 - loss: 0.0698 - val_accuracy: 0.9426 - val_loss: 0.1995
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 141s 62ms/step - accuracy: 

In [59]:
model.save("trained_model.keras")

In [60]:
!ls -lh


total 180M
drwxr-xr-x 1 root root 4.0K Sep  3 13:36 sample_data
-rw-r--r-- 1 root root  90M Sep  8 15:38 trained_model.h5
-rw-r--r-- 1 root root  90M Sep  8 15:38 trained_model.keras


In [62]:
from google.colab import files
files.download("trained_model.h5")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>